### ISSUE TITLE
Extract Merge Step from Tronko Build Into a Separate Command

### ISSUE THREAD

**Issue by jimjeffers** [lpipes/tronko#7]
The operation that performs the final merging of all of the trees processed in tronko build requires a machine with more resources (memory) than the longer running build process. We'd like to have the ability to run this as a separate job on a different machine such that we can utilize a much more cost effective VM to execute the build command.

**Comment by lpipes** [comment]
Let me explain how to use the 2-step tronko-build. To run the first step use new options `-p` and `-r`:
```
tronko-build -y -e example_datasets/multiple_trees/one_MSA -d [full path to output directory] -s -n 1 -p -r
```
This will remove the unused files and exit before the memory intensive step. Now to run the second step:
```
tronko-build -y -e [full path to output directory from step 1] -d [final output directory] -n [number of partitions in the output directory] -v -f [an integer larger than any one partition]
```
You will have to count the number of remaining partitions to get `-n`. You can just count the number of taxonomy files for example. For `-f` you can use a number that is large (but not larger than an int) like 999999.
