### ISSUE TITLE
tronko for ASVs gives segmentation fault

### ISSUE THREAD

**Issue by robinsleith** [lpipes/tronko#8]
Hello, perhaps I am not using this program as intended but I am trying to assign taxonomy of COI ASVs after running a typical dada2 workflow. I have had success when I run paired reads through tronko-assign but passing a fasta file has given the same segmentation fault multiple times on a system with 192 cores and 1Tb of RAM. Example below. Happy to provide test dataset if that would be helpful. Thanks!

```
(base) rsleith@c5-1 testdata $ singularity exec --bind /mnt/storage/data/edna/dada/projects/robin_foo/testdata/ tronko_1.0.sif tronko-assign -r -s -w -C 50 -c 5 -f CO1_tronko_build.txt.gz -a CO1.fasta -g top100_ASV_sequences.fasta -o top100_results.txt
[bwa_index] Pack FASTA... 8.66 sec
[bwa_index] Construct BWT for the packed sequence...
[BWTIncCreate] textLength=800942102, availableWord=68357220
[BWTIncConstructFromPacked] 10 iterations done. 99999990 characters processed.
[BWTIncConstructFromPacked] 20 iterations done. 196686918 characters processed.
[BWTIncConstructFromPacked] 30 iterations done. 282910982 characters processed.
[BWTIncConstructFromPacked] 40 iterations done. 359543142 characters processed.
[BWTIncConstructFromPacked] 50 iterations done. 427649990 characters processed.
[BWTIncConstructFromPacked] 60 iterations done. 488179526 characters processed.
[BWTIncConstructFromPacked] 70 iterations done. 541974310 characters processed.
[BWTIncConstructFromPacked] 80 iterations done. 589783238 characters processed.
[BWTIncConstructFromPacked] 90 iterations done. 632271942 characters processed.
[BWTIncConstructFromPacked] 100 iterations done. 670031942 characters processed.
[BWTIncConstructFromPacked] 110 iterations done. 703589110 characters processed.
[BWTIncConstructFromPacked] 120 iterations done. 733410774 characters processed.
[BWTIncConstructFromPacked] 130 iterations done. 759912310 characters processed.
[BWTIncConstructFromPacked] 140 iterations done. 783462902 characters processed.
[bwt_gen] Finished constructing BWT in 149 iterations.
[bwa_index] 396.03 seconds elapse.
[bwa_index] Update BWT... 4.33 sec
[bwa_index] Pack forward-only FASTA... 6.68 sec
[bwa_index] Construct SA from BWT and Occ... 79.81 sec
Segmentation fault
```

**Comment by lpipes** [comment]
This looks like it's being run correctly. Is it possible for you to provide the file (`top100_ASV_sequences.fasta`) or some of it so I can debug this issue? Thank you.

**Comment by robinsleith** [comment]
Here is a link to the file, let me know if you have trouble accessing it. Thanks!
https://www.dropbox.com/scl/fi/cnu2aimr6ozbfonobb5p0/top100_ASV_sequences.fasta?rlkey=xcner4hwxvh89nhr659n159ce&dl=0

**Comment by lpipes** [comment]
Thank you! The only issue is that `tronko-assign` doesn't expect line breaks. I will update this so that line breaks can be expected. In the meantime you can remove line breaks (`sed -i` makes changes in place) by:
```
sed -i ':a; $!N; /^>/!s/\n\([^>]\)/\1/; ta; P; D' top100_ASV_sequences.fasta
```
If you re-run your analysis with the line breaks removed, it should work. I also recommend adding the `-6` option to skip the `bwa index` build if those files exist already. I added the output here.
[top100_results.txt](https://github.com/user-attachments/files/16371736/top100_results.txt)

**Comment by robinsleith** [comment]
Well that's an easy fix! Works well now. Thanks.
